version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/military_dashboard
      - SECRET_KEY=dev_secret_key_change_in_production
      - ALLOWED_HOSTS=localhost,127.0.0.1

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=military_dashboard

volumes:
  postgres_data:
