# Generated by Django 4.2.5 on 2025-07-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_soldier_service_number_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='branch',
            field=models.CharField(choices=[('Army', 'Army'), ('Navy', 'Navy'), ('Air Force', 'Air Force'), ('Marine Corps', 'Marine Corps'), ('Coast Guard', 'Coast Guard')], default='Army', max_length=20),
        ),
    ]
